### ISSUE TITLE
Test K8s setup

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/s-k8-proxy-rebuild#10]
Test and verify the proposed Kubernetes setups here:
https://github.com/k8-proxy/s-k8-proxy-rebuild/tree/develop/upwork-devs

Each directory contains a proposed K8s setup as a response to requirements of this task:
https://github.com/k8-proxy/s-k8-proxy-rebuild/issues/2

The expected test should cover:

1. Following the steps outlines by the developers to get the k8s node up and running.
2. Identify guidelines gaps or missing information.
3. Verify that the functional requirements are met.
4. Propose enhancements/ideas if possible.

**Comment by mahnouman** [comment]
Hello @azopat please go through the submitted candidate codes and initiate the test, thank you.

**Comment by azopat** [comment]
- pranay : looks ok, tests donne successfully.
- hany : it looks ok as well. There is a typo though because the instruction mention a file entrypoint.sh which doesn't exist. Also he should make the images available for pull.
- so-han : instructions not very clear and i didn't install kompose. i think he should provide the kubernetes manifest files and a  simpler way to set it up.

**Comment by hongson1981** [comment]
@azopat 
I updated README.md file, please check

**Comment by hanyhesham** [comment]
@azopat 

- I fixed the entrypoint.sh typo in my latest commit (still not merged).

- I also added passthrough ingress to replace nodeport, @mahnouman  Could you please merge it so he could test?

- For the images, I will edit them in the main repo and make my current images available for the pull.

**Comment by azopat** [comment]
@hanyhesham  i can test directly from your repo - https://github.com/hanyhesham/s-k8-proxy-rebuild/tree/develop/upwork-devs/hanyhesham to not have to wait for the merge. but is the image now available for pull ?

**Comment by hanyhesham** [comment]
@azopat  I am pushing them now

**Comment by azopat** [comment]
thanks @hanyhesham  , it's working now.

**Comment by azopat** [comment]
K8s installation with kubespray successfull.
But i couldn't test the chart because there are errors here  : 
------
git clone https://github.com/k8-proxy/k8-reverse-proxy.git
git checkout pranay/k8s-setup branch
cd stable-src
----

pranay/k8s-setup branch doesn't exist on this repo https://github.com/k8-proxy/k8-reverse-proxy.git , instead it exist on this repo https://github.com/k8-proxy/s-k8-proxy-rebuild but on that branch i do not see the stable-src folder.

Please clarify that point and let me know

**Comment by pranaysahith** [comment]
@azopat 
The source code for nginx, squid and icap present in https://github.com/k8-proxy/k8-reverse-proxy.git repo.
To build the docker images you need to use pranay-k8s-test branch of this repo. sorry the branch name is incorrect

**Comment by mahnouman** [comment]
@azopat Can you please retest with the correct branch

**Comment by azopat** [comment]
I retested already. everything is ok. I approve the PR
